services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: daylist
      POSTGRES_PASSWORD: daylist
      POSTGRES_DB: daylist
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
